//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordle.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6228f89df9f4b3135d9b5a78_NOBslnCjBjtjzXonGX2vvC7do2ZWazIsHXmT3m14SxkM54vgDo4LP_oQ9Xvep90SESzNqUCOsVsFXLSRJo53cPO_G4Oa48goIS025uldQWJMudngZ5AniBFusRkBI211iJyQolk6 {
            get {
                object obj = ResourceManager.GetObject("6228f89df9f4b3135d9b5a78_NOBslnCjBjtjzXonGX2vvC7do2ZWazIsHXmT3m14SxkM54vgDo4LP_oQ" +
                        "9Xvep90SESzNqUCOsVsFXLSRJo53cPO-G4Oa48goIS025uldQWJMudngZ5AniBFusRkBI211iJyQolk6" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6228f89df9f4b3135d9b5a78_NOBslnCjBjtjzXonGX2vvC7do2ZWazIsHXmT3m14SxkM54vgDo4LP_oQ9Xvep90SESzNqUCOsVsFXLSRJo53cPO_G4Oa48goIS025uldQWJMudngZ5AniBFusRkBI211iJyQolk61 {
            get {
                object obj = ResourceManager.GetObject("6228f89df9f4b3135d9b5a78_NOBslnCjBjtjzXonGX2vvC7do2ZWazIsHXmT3m14SxkM54vgDo4LP_oQ" +
                        "9Xvep90SESzNqUCOsVsFXLSRJo53cPO-G4Oa48goIS025uldQWJMudngZ5AniBFusRkBI211iJyQolk6" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
